# Form implementation generated from reading ui file 'download.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_downloadFrame(object):
    def setupUi(self, downloadFrame):
        downloadFrame.setObjectName("downloadFrame")
        downloadFrame.resize(696, 434)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(downloadFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.downloadNameLabel = QtWidgets.QLabel(parent=downloadFrame)
        self.downloadNameLabel.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.downloadNameLabel.setFont(font)
        self.downloadNameLabel.setWordWrap(True)
        self.downloadNameLabel.setObjectName("downloadNameLabel")
        self.horizontalLayout_4.addWidget(self.downloadNameLabel)
        self.mainProgressBar = QtWidgets.QProgressBar(parent=downloadFrame)
        self.mainProgressBar.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mainProgressBar.setFont(font)
        self.mainProgressBar.setProperty("value", 0)
        self.mainProgressBar.setObjectName("mainProgressBar")
        self.horizontalLayout_4.addWidget(self.mainProgressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.comicDownloadFrame = QtWidgets.QScrollArea(parent=downloadFrame)
        self.comicDownloadFrame.setWidgetResizable(True)
        self.comicDownloadFrame.setObjectName("comicDownloadFrame")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 676, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.comicDownloadFrame.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.comicDownloadFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.downloadsHome = QtWidgets.QPushButton(parent=downloadFrame)
        self.downloadsHome.setEnabled(False)
        self.downloadsHome.setMinimumSize(QtCore.QSize(0, 30))
        self.downloadsHome.setMaximumSize(QtCore.QSize(100, 30))
        self.downloadsHome.setObjectName("downloadsHome")
        self.horizontalLayout.addWidget(self.downloadsHome)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(downloadFrame)
        QtCore.QMetaObject.connectSlotsByName(downloadFrame)

    def retranslateUi(self, downloadFrame):
        _translate = QtCore.QCoreApplication.translate
        downloadFrame.setWindowTitle(_translate("downloadFrame", "Form"))
        self.downloadNameLabel.setText(_translate("downloadFrame", "Loading..."))
        self.downloadsHome.setText(_translate("downloadFrame", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    downloadFrame = QtWidgets.QWidget()
    ui = Ui_downloadFrame()
    ui.setupUi(downloadFrame)
    downloadFrame.show()
    sys.exit(app.exec())
